lint and also found out i may have broken my screenshot keybind command somewhere

diff --git a/herbstluftwm/autostart b/herbstluftwm/autostart
--- a/herbstluftwm/autostart
+++ b/herbstluftwm/autostart
@@ -5,7 +5,7 @@
 ###   LOG FILES   ###
 ##  herbstluftwm's log file  ##
 LOG="${HOME}/LOGS/herbstluftwm.log"
-
+# send the entirety of autostart's execution to the log
 exec > "${LOG}" 2>&1
 
 echo "---  herbstluftwm launching ---"
@@ -141,7 +141,7 @@ hc keybind "${Mod}"-Control-k        spawn "${HOME}/.config/herbstluftwm/scripts
 hc keybind "${Mod}"-Control-comma    spawn "${HOME}/.config/herbstluftwm/scripts/herbstluftwm-save-tree.sh" load
 
 ###   SCREENSHOT SELECTION   ###
-hc keybind "${Mod}"-Shift-s          spawn scrot -s "${HOME}/Pictures/herbstluftwm_screenshots/screenshot_%Y-%m-%d_%H.%M.%S.png" -e "xclip -selection clipboard -t image/png -i ${f}"
+hc keybind "${Mod}"-Shift-s          spawn scrot -s "${HOME}/Pictures/herbstluftwm_screenshots/screenshot_%Y-%m-%d_%H.%M.%S.png" -e xclip -selection clipboard -t image/png -i "${f}"
 
 ###   TAGS SECTION   ###
 
@@ -160,64 +160,67 @@ hc keybind "${Mod}"-Shift-s          spawn scrot -s "${HOME}/Pictures/herbstluft
 # done
 
 ## per-monitor tag lists
-monitor1_tags=( 1 ) # tag names for monitor 1
-monitor2_tags=( 2 ) # tag names for monitor 2
-monitor3_tags=( 3 ) # tag names for monitor 3
+# NOTE: consider naming these tags something cooler like "HMI-1" or "VUI-1" etc
+monitor1_tags=( 1 )         # tag names for monitor 1
+monitor2_tags=( 2 )         # tag names for monitor 2
+monitor3_tags=( 3 )         # tag names for monitor 3
 
-fallback_names=( {4..8} ) # tag names for all other monitors
+auxilliary_tags=( {4..8} )  # tag names for all other monitors
 
-tag_keys=( {1..9} 0 )
+tag_keys=( {1..9} 0 )       # possible keys for use for tags
 
+# rename "default" tag to "monitor1_tags"; || return 1 if prior returns non-zero value
 hc rename default "${monitor1_tags[0]}" || true
-for tag in "${monitor1_tags[@]}" "${monitor2_tags[@]}" "${monitor3_tags[@]}" "${fallback_names[@]}" ; do
-    hc try silent add "$tag"
+# for each tag pointed to by each monitor variable defined by above [@=all arguments]
+for tag in "${monitor1_tags[@]}" "${monitor2_tags[@]}" "${monitor3_tags[@]}" "${auxilliary_tags[@]}" ; do
+    hc try silent add "${tag}"
 done
 
 for i in "${!tag_keys[@]}" ; do
-    key="${tag_keys[$i]}"
+    key="${tag_keys[${i}]}"
     # the keybinding works as follows: the or executes the commands separated by
     # CASE and stops executing them after the first of those succeeds.
     # the first command is: check that we are on monitor 3 and can switch to tag "${monitor1_tags[$i]}"
     # if only one of these two steps fail, try the second one (and so one).
     # The setup for two monitors is as follows:
-    hc keybind "$Mod-$key"                                                          \
-        or CASE and . compare monitors.focus.index = 0 . use "${monitor1_tags[$i]}"    \
-           CASE and . compare monitors.focus.index = 1 . use "${monitor2_tags[$i]}"    \
-           CASE and . compare monitors.focus.index = 2 . use "${monitor3_tags[$i]}"    \
-           CASE use "${fallback_names[$i]}"
-    hc keybind "$Mod-Shift-$key"                                                    \
-        or CASE and . compare monitors.focus.index = 0 . move "${monitor1_tags[$i]}"   \
-           CASE and . compare monitors.focus.index = 1 . move "${monitor2_tags[$i]}"   \
-           CASE and . compare monitors.focus.index = 2 . move "${monitor3_tags[$i]}"   \
-           CASE move "${fallback_names[$i]}"
+    hc keybind "${Mod}-${key}"                                                          \
+        or CASE and . compare monitors.focus.index = 0 . use "${monitor1_tags[${i}]}"   \
+           CASE and . compare monitors.focus.index = 1 . use "${monitor2_tags[${i}]}"   \
+           CASE and . compare monitors.focus.index = 2 . use "${monitor3_tags[${i}]}"   \
+           CASE use "${auxilliary_tags[${i}]}"
+    hc keybind "${Mod}-Shift-${key}"                                                    \
+        or CASE and . compare monitors.focus.index = 0 . move "${monitor1_tags[${i}]}"  \
+           CASE and . compare monitors.focus.index = 1 . move "${monitor2_tags[${i}]}"  \
+           CASE and . compare monitors.focus.index = 2 . move "${monitor3_tags[${i}]}"  \
+           CASE move "${auxilliary_tags[${i}]}"
 done
 
-cycle through tags
-#add additional information in order to cycle only through a monitor's tags
+# cycle through tags
+# add additional information in order to cycle only through a monitor's tags
 # and not through all tags
 define-tag-cycle() {
     local n=$#
     local tags=( "$@" )
     for i in "${!tags[@]}" ; do
-        local t="${tags[$i]}"
-        hc chain , new_attr string tags.by-name."$t".my_previous_tag \
-                 , set_attr tags.by-name."$t".my_previous_tag "${tags[$(((i - 1 + n) % n))]}" \
-                 , new_attr string tags.by-name."$t".my_next_tag \
-                 , set_attr tags.by-name."$t".my_next_tag "${tags[$(((i + 1) % n))]}"
+        local t="${tags[${i}]}"
+        hc chain , new_attr string tags.by-name."${t}".my_previous_tag \
+                 , set_attr tags.by-name."${t}".my_previous_tag "${tags[$(((i - 1 + n) % n))]}" \
+                 , new_attr string tags.by-name."${t}".my_next_tag \
+                 , set_attr tags.by-name."${t}".my_next_tag "${tags[$(((i + 1) % n))]}"
     done
 }
 
 define-tag-cycle "${monitor1_tags[@]}"
 define-tag-cycle "${monitor2_tags[@]}"
 define-tag-cycle "${monitor3_tags[@]}"
-define-tag-cycle "${fallback_names[@]}"
+define-tag-cycle "${auxilliary_tags[@]}"
 
 # cycle through tags
 # check whether the current tag as a custom "next tag" configured
 # if yes, jump to that one, otherwise fall back to ordinary use_index +1
-hc keybind $Mod-period or , substitute NEXT tags.focus.my_next_tag use NEXT  \
+hc keybind "${Mod}"-period or , substitute NEXT tags.focus.my_next_tag use NEXT     \
                           , use_index +1 --skip-visible
-hc keybind $Mod-comma  or , substitute PREV tags.focus.my_previous_tag use PREV  \
+hc keybind "${Mod}"-comma  or , substitute PREV tags.focus.my_previous_tag use PREV \
                           , use_index +1 --skip-visible
 
 
